server:
  port: 8182

spring:
  application:
    name: medihelp-business-tier

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8661/eureka/
  instance:
    hostname: localhost